version: "3.7"

services:
  nginx:
    container_name: laravel-nginx
    image: nginx:latest
    ports:
      - "${DOCKER_NGINX_PORT}:80"
      - "${DOCKER_NGINX_PORT_SSL}:443"
    networks:
      - laravel
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./storage:/storage
      - ./public/docs:/public/docs
    depends_on:
      - php

  php:
    container_name: laravel-php
    build:
      context: ./
      dockerfile: docker/fpm/Dockerfile
    working_dir: /api
    ports:
      - "${DOCKER_PROJECT_IP}:8000:9000"
    networks:
      - laravel
    restart: always
    volumes:
      - ./.:/api
    environment:
      PHP_IDE_CONFIG: "serverName=${DOCKER_PROJECT_DOMAIN}"

  db:
    container_name: laravel-db
    image: mysql:latest
    volumes:
      - laravel-db-vol:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: [
        "--log_bin_trust_function_creators=1",
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ]
    ports:
      - "${DOCKER_PROJECT_IP}:${DOCKER_DB_PORT}:3306"
    networks:
      - laravel
    restart: always

  db-test:
      container_name: laravel-db-test
      image: mysql:latest
      environment:
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      command: [
          "--log_bin_trust_function_creators=1",
          "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      ]
      ports:
          - "${DOCKER_PROJECT_IP}:${DOCKER_DB_PORT_TEST}:3306"
      networks:
          - laravel
      restart: always

networks:
  laravel:
    driver: bridge

volumes:
  laravel-db-vol:
